name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - release-*

parameters:
  - name: cache_nuget
    displayName: Cache NuGet packages
    type: boolean
    default: true
  - name: runSbom
    displayName: Generate & upload SBOM
    type: boolean
    default: true

stages:
  - stage: Build
    displayName: Build & Pack
    jobs:
      - template: .devops/build-and-pack.yml
        parameters:
          solution: Umbraco.Workflow.Automate.slnx
          productName: Umbraco.Workflow.Automate
          cache_nuget: ${{ parameters.cache_nuget }}
          runSbom: ${{ parameters.runSbom }}

  - stage: Test
    dependsOn: Build
    jobs:
      - template: .devops/test.yml
        parameters:
          solution: Umbraco.Workflow.Automate.slnx
