parameters:
  - name: solution
    type: string

jobs:
  - job: UnitTests
    displayName: Unit Tests
    strategy:
      matrix:
        Windows:
          vmImage: 'windows-latest'
        Linux:
          vmImage: 'ubuntu-latest'
        macOS:
          vmImage: 'macos-latest'
    pool:
      vmImage: $(vmImage)
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download build artifacts
        inputs:
          artifact: build_output
          path: $(Build.SourcesDirectory)

      - task: UseDotNet@2
        displayName: Use .NET SDK from global.json
        inputs:
          useGlobalJson: true

      - script: dotnet test ${{ parameters.solution }} --configuration Release --no-build --logger trx --results-directory $(Build.ArtifactStagingDirectory)/tests
        displayName: Run dotnet test

      - task: PublishTestResults@2
        displayName: Publish test results
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '*.trx'
          searchFolder: $(Build.ArtifactStagingDirectory)/tests
          testRunTitle: Unit Tests - $(Agent.OS)
          configuration: Release
